spring:
  thymeleaf:
    cache: false
taco:
  orders:
    pageSize: 10
logging:
  level: debug

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacocloud
    password: tacopassword

logging:
  level: warn